[package]
name = "treez"
version = "0.1.1"
authors = ["Yuan Liu <yuan6liu@gmail.com>"]
description = "A collection of useful tree data structures."
repository = "https://github.com/clearlycloudy/treez/"
keywords = [ "tree", "segment", "algorithm" ]
license = "BSD-2-Clause"

[dependencies]

[lib]
name = "treez"
path = "src/mod.rs"