[package]
name = "treez"
version = "0.1.5"
authors = ["Yuan Liu <yuan6liu@gmail.com>"]
description = "A collection of useful tree data structures."
repository = "https://github.com/clearlycloudy/treez/"
keywords = [ "tree", "segment", "algorithm" ]
license = "BSD-2-Clause"
documentation = "https://docs.rs/treez/0.1.5/treez/"

[dependencies]

[lib]
name = "treez"
path = "src/mod.rs"